### ISSUE TITLE
No writers for methods

### ISSUE THREAD

**Issue by arturictus** [arturictus/contextuable#1]
For example:

``` ruby
c = Contextuable.not_writer_for(:email).new(email: 'asdfsdf@email.com')
c.email = 'other@sdf.com'
# => error
```

Of course the method can be use in the class definition:

``` ruby
class LoginParams <  Contextuable
  not_writer_for :email
end
```

**We can only set the email in the initialization.**

**The method name could be:**
- `not_writer_for``
- `protect``
- `protected`

**Possible error responses:**
- NoMethodError
- NotSetterAllowed with message `trying to set a blocked attribute ´email´ only allowed in initialization`

**Comment by arturictus** [comment]
Carefull with that:

``` ruby
Contextuable.not_writer_for(:email)
```

We are setting `not_writer_for` for the contextuable class it will affect to all the Contextuable's instances. we should return a new anonimous class or wait until initialization and set it in an instance variable.

Anomymous class:

``` ruby
Class.new(Contextuable).not_writer_for(:email)
```

Instance set:

``` ruby
Contextuable.new(email: 'asdfsdf@email.com').not_writer_for(:email)
```

**Comment by arturictus** [comment]
I'm trying this code:

``` ruby
    def email=(a)
      fail "NoOverrideAllowed `:email` for `#{self.class}` at #{better_error(caller, __callee__)}"
    end
    def better_error(_caller, _callee)
      found = nil
      _caller.each do |line|
        found = line  if line.include?(_callee.to_s)
        break if found
      end
      found ? found : _caller.first
    end
```

I would like to get to that:

```
     # ./lib/fcm_us/login_service.rb:8:in `email='
     # ./lib/fcm_us/login_service.rb:50:in `call'
```

But I'm getting:

```
  NoOverrideAllowed `:email` for `FcmUs::LoginParams` at /Users/arturpanach/projects/path_eventor/lib/fcm_us/login_service.rb:50:in `call'
```

**Comment by arturictus** [comment]
#2 removes all the methods in Contextuable class. It only adds basic OpenStruct behaviour.
Now all the magic gets included in the inherited classes
